# Generated by Django 2.2.6 on 2019-12-08 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CASUser',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=20)),
                ('last_name', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('first_time', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('storage_size', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sublet.CASUser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('c_type', models.CharField(max_length=50)),
                ('data', models.BinaryField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sublet.Listing')),
            ],
        ),
    ]
