# Generated by Django 2.2.6 on 2019-12-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublet', '0002_auto_20191208_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='storage_size',
        ),
        migrations.AddField(
            model_name='listing',
            name='form_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
