# Generated by Django 2.2.6 on 2019-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublet', '0003_auto_20191208_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='img_id',
            field=models.CharField(default=None, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
