# Generated by Django 2.2.6 on 2019-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sublet', '0004_auto_20191208_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_completion',
            field=models.BooleanField(default=False),
        ),
    ]
